name: Docker CI - Build & Push to GCP Artifact Registry

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: winppk-app01
  REGION: us-central1
  REPO: todorepo
  IMAGE_NAME: todoimg
  IMAGE_TAG: todotag

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write   # REQUIRED for OIDC

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Authenticate to GCP (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/POOL_ID/providers/PROVIDER_ID
          service_account: github-ci@winppk-app01.iam.gserviceaccount.com

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Docker build
        run: |
          docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .

      - name: Docker images (verify)
        run: |
          docker images

      - name: Docker tag
        run: |
          docker tag ${IMAGE_NAME}:${IMAGE_TAG} \
            ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/${IMAGE_NAME}:${IMAGE_TAG}

      - name: Docker push
        run: |
          docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/${IMAGE_NAME}:${IMAGE_TAG}
